### ISSUE TITLE
Tests - login/test_redirect: Check that the redirected page is correct

### ISSUE THREAD

**Issue by skairunner** [skairunner/pctnet#33]
Currently the test only checks that a redirect happens at all. It should probably check that the page it is redirected to is, indeed, the front page.

**Comment by vdkotian** [comment]
Hello, I am looking forward to contributing towards this project. Is this issue or any other issue open?

**Comment by skairunner** [comment]
The open issues are open. This issue in question is fairly easy to fix, I just haven't gotten around to it. It would be helpful if you do!

**Comment by vdkotian** [comment]
I have started working on this issue. I have gone through the code and probably the change is login/tests.py test_redirect (in this function or somewhere around the called functions). It would be helpful if you could elaborate on what exactly are you looking for.
As per my understanding, your existing code is redirecting the newly created user is redirected to the home/front page ('/user/5/alexander-hamilton/'). So what exactly are you looking for?

**Comment by skairunner** [comment]
Ah, it seems that while adding a redirect test to a different page, 0e9fc4909204828570cee510150303d62d3e0b64 also added a redirect test for the login case. Apologies for the confusion.
